package ru.said.miami.orm.core.cache.core.field;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Created by said on 25.02.17.
 */

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface TableField {
    String fieldName();

    String defaultValue() default "";

    boolean id() default false;

    boolean autoGeneratedId() default false;

    boolean canBeNull() default true;

    DataType dataType() default DataType.UNKNOWN;

    boolean foreignKey() default false;
}
