package test_table;

import field.*;
import table.Table;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by said on 02.05.17.
 */
@Table(name = "foo")
public class Foo {
    @TableField(id = true, autoGeneratedId = true, dataType = DataType.LONG, fieldName = "id")
    private long id;

    @TableField(dataType = DataType.STRING, fieldName = "test_name")
    private String name;

    @OneToOne
    @TableField(canBeNull = false, dataType = DataType.INTEGER, fieldName = "foo1_id")
    Foo1 foo1;

    @OneToMany(mappedBy = "foo")
    List<Foo2> foo2List = new ArrayList<>();

    @ManyToMany(mappedBy = "fooList")
    List<Foo3> foo3List = new ArrayList<>();

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setFoo1(Foo1 foo1) {
        this.foo1 = foo1;
    }

    public List<Foo2> getFoo2List() {
        return foo2List;
    }

    public Foo1 getFoo1() {
        return foo1;
    }

    public List<Foo3> getFoo3List() {
        return foo3List;
    }

    @Override
    public String toString() {
        return "test_table.Foo{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }



}
