package test_table;

import field.DBField;
import field.DataType;
import field.ManyToMany;
import field.ManyToOne;
import table.DBTable;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by said on 02.05.17.
 */
@DBTable(name = "foo1")
public class Foo1 {
    @DBField(id = true, autoGeneratedId = true, dataType = DataType.LONG, fieldName = "id")
    private long id;

    @DBField(dataType = DataType.STRING, fieldName = "test_name")
    private String name;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Foo1{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
