package utils;

import field.Field;
import org.apache.log4j.Logger;
import support.JDBCConnectionSource;
import table.Table;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by said on 25.02.17.
 */
public class TableUtils {

    private final static Logger LOGGER = Logger.getLogger(TableUtils.class);

    private TableUtils() {
    }

    public static<T> void createTable(JDBCConnectionSource connectionSource, Class<T> dbTable) throws SQLException {
        String dbTableName = dbTable.getAnnotation(Table.class).name();
        StringBuilder sbCreateTable = new StringBuilder();

        sbCreateTable.append("CREATE TABLE ").append(dbTableName).append("(");
        for (java.lang.reflect.Field field: dbTable.getDeclaredFields()) {
            if (field.isAnnotationPresent(Field.class)) {
                sbCreateTable.append(field.getAnnotation(Field.class).fieldName()).append(" ");
                sbCreateTable.append(field.getAnnotation(Field.class).dataType().toString()).append(" ");
                sbCreateTable.append(field.getAnnotation(Field.class).id() ? "PRIMARY KEY" : "").append(" ");
                if (field.getAnnotation(Field.class).autoGeneratedId()) {
                    sbCreateTable.append("AUTOINCREMENT").append(", ");
                } else {
                    sbCreateTable.append(field.getAnnotation(Field.class).canBeNull() ? "NULL" : "NOT NULL").append(", ");
                }
            }
        }
        sbCreateTable.replace(sbCreateTable.length() - 2, sbCreateTable.length(), ")");
        Statement statement = null;
        Connection connection = connectionSource.getConnection();

        try {
            statement = connection.createStatement();
            statement.execute(sbCreateTable.toString());
            LOGGER.debug(sbCreateTable.toString());
        } finally {
            if (statement != null) {
                statement.close();
            }
            connectionSource.releaseConnection(connection);
        }
    }

    public static<T> void dropTable(JDBCConnectionSource connectionSource, Class<T> dbTable) throws SQLException {
        String dropTableSQL = "DROP TABLE " + dbTable.getAnnotation(Table.class).name();
        Statement statement = null;
        Connection connection = connectionSource.getConnection();

        try {
            statement = connection.createStatement();
            statement.execute(dropTableSQL);
            LOGGER.debug(dropTableSQL);
        } finally {
            if (statement != null) {
                statement.close();
            }
            connectionSource.releaseConnection(connection);
        }
    }

    public static<T> void clearTable(JDBCConnectionSource connectionSource, Class<T> dbTable) throws SQLException {
        String truncateTableSQL = "DELETE FROM " + dbTable.getAnnotation(Table.class).name();
        Statement statement = null;
        Connection connection = connectionSource.getConnection();

        try {
            statement = connection.createStatement();
            statement.execute(truncateTableSQL);
            LOGGER.debug(truncateTableSQL);
        } finally {
            if (statement != null) {
                statement.close();
            }
            connectionSource.releaseConnection(connection);
        }
    }
}
