package utils;

import com.sun.javadoc.FieldDoc;
import field.DBField;
import field.OneToOne;
import org.apache.log4j.Logger;
import support.JDBCConnectionSource;
import table.DBTable;
import table.TableInfo;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by said on 25.02.17.
 */
public class TableUtils {

    private final static Logger LOGGER = Logger.getLogger(TableUtils.class);

    private TableUtils() {
    }

    public static <T> void createTable(JDBCConnectionSource connectionSource, Class<T> dbTable) throws SQLException {
        TableInfo<T> tableInfo = new TableInfo<>(dbTable);
        StringBuilder sbCreateTable = new StringBuilder();

        sbCreateTable.append("CREATE TABLE ").append(tableInfo.getTableName()).append("(");
        Field id = tableInfo.getId();

        if (id != null) {
            sbCreateTable.append(id.getAnnotation(DBField.class).fieldName()).append(" ");
            sbCreateTable.append(id.getAnnotation(DBField.class).dataType().toString()).append(" ");
            sbCreateTable.append(id.getAnnotation(DBField.class).id() ? "PRIMARY KEY" : "").append(" ");
            if (id.getAnnotation(DBField.class).autoGeneratedId()) {
                sbCreateTable.append("AUTOINCREMENT").append(", ");
            }
        }
        for (java.lang.reflect.Field field : tableInfo.getFields()) {
            appendField(field, sbCreateTable);
        }
        for (Field field: tableInfo.getOneToOneRelations()) {
            appendField(field, sbCreateTable);
        }
        for (Field field: tableInfo.getManyToOneRelations()) {
            appendField(field, sbCreateTable);
        }
        for (Field field: tableInfo.getOneToOneRelations()) {
            appendForeignKey(field, sbCreateTable);
        }
        for (Field field: tableInfo.getManyToOneRelations()) {
            appendForeignKey(field, sbCreateTable);
        }
        sbCreateTable.replace(sbCreateTable.length() - 2, sbCreateTable.length(), ");");
        Statement statement = null;
        Connection connection = connectionSource.getConnection();

        try {
            statement = connection.createStatement();
            statement.execute(sbCreateTable.toString());
            LOGGER.debug(sbCreateTable.toString());
        } finally {
            if (statement != null) {
                statement.close();
            }
            connectionSource.releaseConnection(connection);
        }
    }

    private static void appendField(Field field, StringBuilder sb) {
        sb.append(field.getAnnotation(DBField.class).fieldName()).append(" ");
        sb.append(field.getAnnotation(DBField.class).dataType().toString()).append(" ");
        sb.append(field.getAnnotation(DBField.class).id() ? "PRIMARY KEY" : "").append(" ");
        sb.append(field.getAnnotation(DBField.class).canBeNull() ? "NULL" : "NOT NULL").append(", ");
    }

    private static void appendForeignKey(Field field, StringBuilder sb) {
        TableInfo tableInfo = new TableInfo(field.getType());

        sb.append("FOREIGN KEY ")
                .append("(")
                .append(field.getAnnotation(DBField.class).fieldName())
                .append(") ")
                .append("REFERENCES ")
                .append(field.getType().getAnnotation(DBTable.class).name())
                .append("(")
                .append(tableInfo.getId().getAnnotation(DBField.class).fieldName())
                .append("));");
    }

    public static <T> void dropTable(JDBCConnectionSource connectionSource, Class<T> dbTable) throws SQLException {
        String dropTableSQL = "DROP TABLE " + dbTable.getAnnotation(DBTable.class).name();
        StatementExecutor.execute(connectionSource, dropTableSQL);
    }

    public static <T> void clearTable(JDBCConnectionSource connectionSource, Class<T> dbTable) throws SQLException {
        String truncateTableSQL = "DELETE FROM " + dbTable.getAnnotation(DBTable.class).name();
        StatementExecutor.execute(connectionSource, truncateTableSQL);
    }
}
