package test;

import field.Field;
import field.DataType;
import table.Table;

/**
 * Created by said on 25.02.17.
 */
@Table(name = "test")
public class Test {

    @Field(id = true, autoGeneratedId = true, dataType = DataType.LONG, fieldName = "id")
    private long id;

    @Field(dataType = DataType.STRING, fieldName = "test_name")
    private String name;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Test{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
