package test;

import field.DBField;
import field.DataType;
import field.OneToMany;
import field.OneToOne;
import support.ForeignCollection;
import table.DBTable;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by said on 25.02.17.
 */
@DBTable(name = "test")
public class Test {

    @DBField(id = true, autoGeneratedId = true, dataType = DataType.LONG, fieldName = "id")
    private long id;

    @DBField(dataType = DataType.STRING, fieldName = "test_name")
    private String name;

    @OneToMany(mappedBy = "test")
    private List<Test1> test1Coll = new ArrayList<>();

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Test{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    public List<Test1> getTest1Coll() {
        return test1Coll;
    }
}
