package test;

import field.DBField;
import field.DataType;
import field.ManyToOne;
import table.DBTable;

/**
 * Created by said on 18.03.17.
 */

@DBTable(name = "test1")
public class Test1 {

    @DBField(id = true, autoGeneratedId = true, dataType = DataType.LONG, fieldName = "id")
    private long id;

    @DBField(dataType = DataType.STRING, fieldName = "test_name")
    private String name;

    @ManyToOne
    @DBField(canBeNull = false, dataType = DataType.INTEGER, fieldName = "test_id")
    Test test;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Test getTest() {
        return test;
    }

    public void setTest(Test test) {
        this.test = test;
    }

    @Override
    public String toString() {
        return "Test1{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
