package test;

import field.DBField;
import field.DataType;
import field.ManyToMany;
import field.ManyToOne;
import table.DBTable;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by said on 18.03.17.
 */

@DBTable(name = "test1")
public class Test1 {

    @DBField(id = true, autoGeneratedId = true, dataType = DataType.LONG, fieldName = "id")
    private long id;

    @DBField(dataType = DataType.STRING, fieldName = "test_name")
    private String name;


    @ManyToMany(mappedBy = "test1Coll")
    List<Test> testColl = new ArrayList<>();

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Test> getTestColl() {
        return testColl;
    }

    @Override
    public String toString() {
        return "Test1{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
