import field.DBField;
import field.DataType;
import table.DBTable;

/**
 * Created by said on 09.05.17.
 */
@DBTable(name = "test2")
public class Test {

    @DBField(fieldName = "id", id = true, autoGeneratedId = true, canBeNull = false, dataType = DataType.LONG)
    private long id;

    @DBField(fieldName = "name", dataType = DataType.STRING)
    private String name;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
