package ru.said.miami.orm.core;

import ru.said.miami.orm.core.field.DBField;
import ru.said.miami.orm.core.table.DBTable;

/**
 * Join table which links users to their posts.
 * 
 * <p>
 * For more information about foreign objects, see the <a href="http://ormlite.com/docs/foreign" >online docs</a>
 * </p>
 */
@DBTable(name = "user_post")
public class UserPost {

	public final static String USER_ID_FIELD_NAME = "user_id";
	public final static String POST_ID_FIELD_NAME = "post_id";

	/**
	 * This id is generated by the database and set on the object when it is passed to the create method. An id is
	 * needed in case we need to update or delete this object in the future.
	 */
	@DBField(id = true, generated = true)
	int id;

	// This is a foreign object which just stores the id from the User object in this table.
	@DBField(foreign = true, columnName = USER_ID_FIELD_NAME)
    User user;

	// This is a foreign object which just stores the id from the Post object in this table.
	@DBField(foreign = true, columnName = POST_ID_FIELD_NAME)
    Post post;

	UserPost() {
		// for ormlite
	}

	public UserPost(User user, Post post) {
		this.user = user;
		this.post = post;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Override
	public String toString() {
		return "UserPost{" +
				"id=" + id +
				", user=" + user +
				", post=" + post +
				'}';
	}
}
