package ru.said.miami.orm.core;

import ru.said.miami.orm.core.field.DBField;
import ru.said.miami.orm.core.field.Getter;
import ru.said.miami.orm.core.field.Setter;
import ru.said.miami.orm.core.table.DBTable;

/**
 * A user object with a name.
 */
@DBTable(name = "user")
public class User {

	// we use this field-name so we can query for users with a certain id
	public final static String ID_FIELD_NAME = "id";

	// this id is generated by the database and set on the object when it is passed to the create method
	@Getter(name = "getId")
	@Setter(name = "setId")
	@DBField(id = true, generated = true, columnName = ID_FIELD_NAME)
	int id;

	@Getter(name = "getName")
	@Setter(name = "setName")
	@DBField
	String name;

	User() {
		// for ormlite
	}

	public User(String name) {
		this.name = name;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "User{" +
				"id=" + id +
				", name='" + name + '\'' +
				'}';
	}
}
