package utils.test;

import field.TableField;
import field.DataType;
import table.Table;

/**
 * Created by said on 09.05.17.
 */
@Table(name = "test2")
public class Test {

    @TableField(fieldName = "id", id = true, autoGeneratedId = true, canBeNull = false, dataType = DataType.LONG)
    public long id;

    @TableField(fieldName = "name", dataType = DataType.STRING)
    public String name;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
